sudo: required

language: node_js
node_js:
    - "10"

dist: trusty
sudo: false

cache:
    yarn: true
    directories:
        - node_modules

addons:
    chrome: stable

install:
    - yarn

script:
    - yarn ci:pipelines
