sudo: required
dist: trusty

language: node_js
node_js:
    - "10"

dist: trusty
sudo: false

cache:
    yarn: true
    directories:
        - node_modules

addons:
    chrome: stable

before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"

install:
    - yarn

script:
    - yarn ci:pipelines
